config/routes.rb
TrekkingByJfk::Application.routes.draw do
  resources :searches

  resources :posts

  resources :comments

  resources :rates

  resources :markers

  resources :users

  
  match "/desc/:id" => "markers#desc"
  root :to => "users#index"

end

app/models/marker.rb
class Marker < ActiveRecord::Base
	has_many :posts
	
	attr_accessor :name, :url

  validates :name,  :presence => true
  validates :posX,  :presence => true
  validates :posY,  :presence => true
end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  # GET /markers
  # GET /markers.json
  def index
    @markers = Marker.order("name").page(params[:page]).per(4)#Marker.all
	  @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @markers }
    end
  end

  # GET /markers/1
  # GET /markers/1.json
  def show
    @markers = Marker.order("name").page(params[:page]).per(4)#Marker.all

    @marker = Marker.find(params[:id])

	  @map = Cartographer::Gmap.new( 'map' )
	  @map.zoom = :bound
	  @map.debug = true
	  normal_icon = Cartographer::Gicon.new
	  @map.icons << normal_icon
    marker1 = Cartographer::Gmarker.new(:name=> @marker.name, :marker_type => "Building",
        :position => [@marker.posX, @marker.posY], :icon => normal_icon,
		:info_window_url => @marker.url)
	  @map.markers << marker1
	
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @marker }
    end
  end

  # GET /markers/new
  # GET /markers/new.json
  def new
    @markers = Marker.order("name").page(params[:page]).per(4)#Marker.all
    @marker = Marker.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @marker }
    end
  end

  # GET /markers/1/edit
  def edit
	@markers = Marker.order("name").page(params[:page]).per(4)#Marker.all
    @marker = Marker.find(params[:id])
  end

  # POST /markers
  # POST /markers.json
  def create
	@markers = Marker.order("name").page(params[:page]).per(4)#Marker.all
    @marker = Marker.new(params[:marker])

    respond_to do |format|
      if @marker.save
        format.html { redirect_to @marker, notice: 'Marker was successfully created.' }
        format.json { render json: @marker, status: :created, location: @marker }
      else
        format.html { render action: "new" }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /markers/1
  # PUT /markers/1.json
  def update
	@markers = Marker.order("name").page(params[:page]).per(4)#Marker.all
    @marker = Marker.find(params[:id])

    respond_to do |format|
      if @marker.update_attributes(params[:marker])
        format.html { redirect_to @marker, notice: 'Marker was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markers/1
  # DELETE /markers/1.json
  def destroy
	@markers = Marker.order("name").page(params[:page]).per(4)#Marker.all
    @marker = Marker.find(params[:id])
    @marker.destroy

    respond_to do |format|
      format.html { redirect_to markers_url }
      format.json { head :ok }
    end
  end
  
  def desc
	render :text => "Informacje o " + params[:id]
  end
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/views/markers/_form.html.erb
<%= form_for(@marker) do |f| %>
  <% if @marker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@marker.errors.count, "error") %> prohibited this marker from being saved:</h2>

      <ul>
      <% @marker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :posX %><br />
    <%= f.text_field :posX %>
  </div>
  <div class="field">
    <%= f.label :posY %><br />
    <%= f.text_field :posY %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/markers/edit.html.erb
<h1>Edycja markera</h1>

<%= render 'form' %>

<%= link_to 'Show', @marker %> |
<%= link_to 'Back', markers_path %>

app/views/markers/index.html.erb
<h1>Markery</h1>

<table>
  <tr>
    <th>Nazwa</th>
    <th>Pozycja X</th>
    <th>Pozycja Y</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @markers.each do |marker| %>
  <tr>
    <td><%= marker.name %></td>
    <td><%= marker.posX %></td>
    <td><%= marker.posY %></td>
    <td><%= marker.url %></td>
    <td><%= link_to 'Show', marker %></td>
    <td><%= link_to 'Edit', edit_marker_path(marker) %></td>
    <td><%= link_to 'Destroy', marker, confirm: 'Na pewno?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nowy Marker', new_marker_path %>

app/views/markers/new.html.erb
<h1>Nowy marker</h1>

<%= render 'form' %>

<%= link_to 'Back', markers_path %>

app/views/markers/show.html.erb
<p id="notice"><%= notice %></p>

<%= raw Cartographer::Header.new.to_s %>
  <%= raw @map.to_html %>
  <div style="width:600px;height:400px;" id="map" > [Map] </div>
<br />

<p>
	<div class="exemple">
		<b>Ocena miejsca:</b>
		<div class="exemple5" data="10_5"></div>
	</div>
</p>

<p>
  <b>Nazwa:</b>
  <%= @marker.name %>
</p>

<p>
  <b>X:</b>
  <%= @marker.posX %>
</p>

<p>
  <b>Y:</b>
  <%= @marker.posY %>
</p>

<p>
  <b>Url:</b>
  <%= @marker.url %>
</p>

<%= link_to 'Edytuj', edit_marker_path(@marker) %> |
<%= link_to 'Z powrotem', markers_path %>