config/routes.rb
TrekkingByJfk::Application.routes.draw do
  resources :searches

  resources :posts

  resources :comments

  resources :rates

  resources :markers

  resources :users

  
  match "/desc/:id" => "markers#desc"
  root :to => "users#index"

end

app/models/rate.rb
class Rate < ActiveRecord::Base
	belongs_to 	:marker
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  # GET /rates
  # GET /rates.json
  def index
    @rates = Rate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rates }
    end
  end

  # GET /rates/1
  # GET /rates/1.json
  def show
    @rate = Rate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rate }
    end
  end

  # GET /rates/new
  # GET /rates/new.json
  def new
    @rate = Rate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rate }
    end
  end

  # GET /rates/1/edit
  def edit
    @rate = Rate.find(params[:id])
  end

  # POST /rates
  # POST /rates.json
  def create
    @rate = Rate.new(params[:rate])

    respond_to do |format|
      if @rate.save
        format.html { redirect_to @rate, notice: 'Rate was successfully created.' }
        format.json { render json: @rate, status: :created, location: @rate }
      else
        format.html { render action: "new" }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rates/1
  # PUT /rates/1.json
  def update
    @rate = Rate.find(params[:id])

    respond_to do |format|
      if @rate.update_attributes(params[:rate])
        format.html { redirect_to @rate, notice: 'Rate was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rates/1
  # DELETE /rates/1.json
  def destroy
    @rate = Rate.find(params[:id])
    @rate.destroy

    respond_to do |format|
      format.html { redirect_to rates_url }
      format.json { head :ok }
    end
  end
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/views/rates/_form.html.erb
<%= form_for(@rate) do |f| %>
  <% if @rate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rate.errors.count, "error") %> prohibited this rate from being saved:</h2>

      <ul>
      <% @rate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sum %><br />
    <%= f.text_field :sum %>
  </div>
  <div class="field">
    <%= f.label :votes %><br />
    <%= f.text_field :votes %>
  </div>
  <div class="field">
    <%= f.label :marker %><br />
    <%= f.text_field :marker %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rates/edit.html.erb
<h1>Editing rate</h1>

<%= render 'form' %>

<%= link_to 'Show', @rate %> |
<%= link_to 'Back', rates_path %>

app/views/rates/index.html.erb
<h1>Listing rates</h1>

<table>
  <tr>
    <th>Sum</th>
    <th>Votes</th>
    <th>Marker</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rates.each do |rate| %>
  <tr>
    <td><%= rate.sum %></td>
    <td><%= rate.votes %></td>
    <td><%= rate.marker %></td>
    <td><%= link_to 'Show', rate %></td>
    <td><%= link_to 'Edit', edit_rate_path(rate) %></td>
    <td><%= link_to 'Destroy', rate, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rate', new_rate_path %>

app/views/rates/new.html.erb
<h1>New rate</h1>

<%= render 'form' %>

<%= link_to 'Back', rates_path %>

app/views/rates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sum:</b>
  <%= @rate.sum %>
</p>

<p>
  <b>Votes:</b>
  <%= @rate.votes %>
</p>

<p>
  <b>Marker:</b>
  <%= @rate.marker %>
</p>


<%= link_to 'Edit', edit_rate_path(@rate) %> |
<%= link_to 'Back', rates_path %>